source "https://rubygems.org"

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem "bootstrap", "~> 4.0.0.beta2.1"
gem "cancancan"
gem "coffee-rails", "~> 4.2"
gem "config"
gem "devise"
gem "font-awesome-rails"
gem "jbuilder", "~> 2.5"
gem "jquery-rails"
gem "kaminari"
gem "mysql2", ">= 0.3.18", "< 0.5"
gem "puma", "~> 3.0"
gem "rack-cors"
gem "rails", "~> 5.0.4"
gem "sass-rails", "~> 5.0"
gem "toastr-rails"
gem "uglifier", ">= 1.3.0"
gem "kaminari"
gem "carrierwave", "0.10.0"
gem "mini_magick", "3.8.0"
gem "fog", "1.36.0"

group :development, :test do
  gem "byebug", platform: :mri
  gem "pry-byebug"
end

group :development do
  gem "web-console", ">= 3.3.0"
  gem "listen", "~> 3.0.5"
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
end

gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
