default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_bin
  pool: 5
  host: 127.0.0.1
  username: test
  password: test

test:
  <<: *default
  adapter: mysql2
  database: ci_test
