project_type: ruby
test:
  bundle-audit:
    command: bundle-audit check --update > .framgia-ci-reports/bundle-audit.txt
  rspec:
    command: rspec --format html --out .framgia-ci-reports/rspec.html spec/
  brakeman:
    command: brakeman -o .framgia-ci-reports/brakeman.html -o .framgia-ci-reports/brakeman.json
  reek:
    command: reek --format html > .framgia-ci-reports/reek.html
  rubocop:
    command: bundle exec rubocop --require rubocop/formatter/checkstyle_formatter --format RuboCop::Formatter::CheckstyleFormatter --no-color --rails --out .framgia-ci-reports/rubocop.xml app/ lib/
  scss-lint:
    ignore: true
    command: scss-lint --require=scss_lint_reporter_checkstyle --format=Checkstyle --out=.framgia-ci-reports/scss-lint.xml app/assets/stylesheets/; ec=$?; if [ $ec -eq 0 -o $ec -eq 1 ]; then (exit 0); else (exit $ec); fi;
  eslint:
    ignore: true
    command: eslint --format=checkstyle --output-file=.framgia-ci-reports/eslint.xml app/
